@containerid = {{$dotenv CONTAINER_ID}}
@hostname = {{$dotenv HOSTNAME}}
@envname = {{$dotenv ENV_NAME}}

GET http://{{hostname}}:4566/restapis/{{containerid}}/{{envname}}/_user_request_/jobs HTTP/1.1
Content-Type: application/json
