POST http://localhost:4566/restapis/1ukcmjojyy/local/_user_request_/todos HTTP/1.1

{"text": "create a localstack POC","checked": false}


curl -H 'Content-Type: application/json' -X POST -d '{"text": "create a localstack POC","checked": false}' http://localhost:4566/restapis/ygnh1tokgq/local/_user_request_/todos

curl -H 'Content-Type: application/json' \
      -d '{ "title":"foo","body":"bar", "id": 1}' \
      -X POST \
      https://example.com/posts

serverless-localstack-poc_default
faa80287daf812541ab91bbdd07d5005edc4d87296b813c72d15642b21a2eaea
