@hostname = localhost
@containerid = 1ukcmjojyy
@envname = local
@itemid = e6e23320-a53f-11ed-82dd-95fbb87ebda9
GET http://{{hostname}}:4566/restapis/{{containerid}}/{{envname}}/_user_request_/todos/{{itemid}} HTTP/1.1
Content-Type: application/json
