@hostname = localhost
@containerid = kvezslqnjj
@envname = local
@itemid = bd8abca0-a61a-11ed-9a30-e5dac4160c17
PUT http://{{hostname}}:4566/restapis/{{containerid}}/{{envname}}/_user_request_/todos/{{itemid}} HTTP/1.1
Content-Type: application/json

{"text": "the localstack POC is created","checked": true}
